#!/bin/sh
lb config noauto                                            \
  --parent-mirror-bootstrap http://ftp.us.debian.org/debian \
  --archive-areas "main contrib non-free"                   \
  --cache-packages true                                     \
  --mode debian                                             \
  --distribution wheezy                                     \
  --binary-images net                                       \
  --ignore-system-defaults                                  \
  --apt-indices false                                       \
  --initramfs-compression gzip                              \
  --gzip-options "--best"                                   \
  "${@}"
